### ISSUE TITLE
Add github badges to scalarm repos 

### ISSUE THREAD

**Issue by groundnuty** [Scalarm/summer-internship-2017#17]
This set of badges is perfect for our needs:
https://github.com/groundnuty/k8s-wait-for

please add them to all the repos that are handled by Travis.
Code quality is of particular interest here :)

**Comment by Dragner8** [comment]
Added codacy to scalarm_experiment_manager, scalarm_experiment_supervisor, scalarm_data_manager to checked code quality

**Comment by groundnuty** [comment]
please provider links to your forks.
links are always a good idea!

**Comment by Dragner8** [comment]
all forks were marge with original scalarm repo
