### ISSUE TITLE
Create a travis configuration file for repo scalamr/scalarm_experiment_manager

### ISSUE THREAD

**Issue by groundnuty** [Scalarm/summer-internship-2017#3]
The Travis flow should:
build the application with running tests (https://github.com/Scalarm/scalarm_experiment_manager)
test if it's working using some acceptance tests
create a docker container with a working package in it
upload the container to docker hub

**Comment by Dragner8** [comment]
Added travis to scalarm_experiment_manager to autimatically build the application without test (problem with passing), next create a docker image and push it to scalarm organization repository
