### ISSUE TITLE
Make scalarm_experiment_manager docker image build automaticaly on docker hub  

### ISSUE THREAD

**Issue by groundnuty** [Scalarm/summer-internship-2017#6]
Link this GitHub repo to Docker hub:
https://github.com/Scalarm/scalarm_experiment_manager
setup the workflow so that every change to the github repo triggers a new container build on Docker hub. 

Investigate if it's possible to run some tests in that workflow prior to image building (probably not).

**Comment by wiki360** [comment]
Can't make automated build without access to https://github.com/Scalarm/scalarm_experiment_manager repo.

**Comment by kliput** [comment]
@skalawi added permissions, you can check

**Comment by kliput** [comment]
@skalawi Oh wait - what do you want to do using write permissions to repo :)? Not commits, but only setup automated build with Travis?

**Comment by wiki360** [comment]
@kliput Only automated build on docker hub

**Comment by wiki360** [comment]
Created automated build of scalarm experiment manager on docker hub: https://hub.docker.com/r/scalarm/scalarm_experiment_manager/
