### ISSUE TITLE
Prepare docker-compose Scalarm main services 

### ISSUE THREAD

**Issue by groundnuty** [Scalarm/summer-internship-2017#7]
With mine and @kliput help, please make this docker-compose work:
https://github.com/Scalarm/summer-internship-2017/blob/master/docker-compose.yml
and test it the resulting deployment thoroughly.

**Comment by kliput** [comment]
Now I'm working to start at least dockerized experiment manager with docker-compose. Work in progress on branch: https://github.com/Scalarm/summer-internship-2017/tree/docker-compose
