### ISSUE TITLE
Make Data Explorer docker image build automaticaly on docker hub enhancement

### ISSUE THREAD

**Issue by groundnuty** [Scalarm/summer-internship-2017#9]
The same story as in the case of experiment manager.

**Comment by wiki360** [comment]
Again, access is needed. Here, I need Dockerfile added to the repo as well.

**Comment by kliput** [comment]
@skalawi Permissions added, also added write permissions to experiment supervisor (just in case?)

> I need Dockerfile added to the repo as well.

There were no Dockerfile for data explorer yet... One of team members should prepare it.

**Comment by wiki360** [comment]
Added Dockerfile to Data Explorer repo and created automatic build on Docker hub.
https://hub.docker.com/r/scalarm/scalarm_data_explorer/
